# Generated by Django 5.2.7 on 2025-10-30 17:06

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GamingStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Unique name for the gaming station', max_length=50, unique=True)),
                ('station_type', models.CharField(choices=[('PC', 'Gaming PC'), ('PS5', 'PlayStation 5'), ('XBOX', 'Xbox Series X'), ('SWITCH', 'Nintendo Switch'), ('VR', 'VR Gaming Setup')], help_text='Type of gaming station', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the gaming station')),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Hourly rate in dollars', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the station is available for booking')),
                ('is_maintenance', models.BooleanField(default=False, help_text='Whether the station is under maintenance')),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Technical specifications like CPU, GPU, RAM, etc.')),
                ('image', models.ImageField(blank=True, help_text='Station photo', null=True, upload_to='stations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gaming Station',
                'verbose_name_plural': 'Gaming Stations',
                'ordering': ['station_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(help_text='Booking start time')),
                ('end_time', models.DateTimeField(help_text='Booking end time')),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Hourly rate at time of booking', max_digits=6)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount for the booking', max_digits=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='PENDING', max_length=20)),
                ('payment_id', models.CharField(blank=True, help_text='Payment gateway transaction ID', max_length=100)),
                ('payment_status', models.CharField(blank=True, help_text='Payment status from gateway', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the booking')),
                ('is_walk_in', models.BooleanField(default=False, help_text='Whether this is a walk-in booking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Customer who made the booking', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='authentication.customer')),
                ('gaming_station', models.ForeignKey(help_text='Gaming station being booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.gamingstation')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for status change')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='booking.booking')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking History',
                'verbose_name_plural': 'Booking Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='booking_end_after_start'),
        ),
    ]
