# Generated by Django 5.2.7 on 2025-10-31 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_notification'),
    ]

    operations = [
    ]
