# Generated by Django 5.2.7 on 2025-10-31 06:34

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20251031_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Game name (e.g., '8-Ball Pool', 'Table Tennis', 'PS4 Console 1')", max_length=100, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the game/activity')),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of players (1 for PC, 4 for pool table)')),
                ('booking_type', models.CharField(choices=[('SINGLE', 'Single Booking (Private Only)'), ('HYBRID', 'Hybrid Booking (Private + Shared)')], help_text='Single (private only) or Hybrid (private + shared)', max_length=10)),
                ('opening_time', models.TimeField(help_text='Daily opening time (e.g., 11:00 AM)')),
                ('closing_time', models.TimeField(help_text='Daily closing time (e.g., 11:00 PM)')),
                ('slot_duration_minutes', models.PositiveIntegerField(default=60, help_text='Duration of each slot in minutes')),
                ('available_days', models.JSONField(default=list, help_text="List of available weekdays ['monday', 'tuesday', ...]")),
                ('private_price', models.DecimalField(decimal_places=2, help_text='Price for private booking (full capacity)', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('shared_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price per spot for shared booking (only for hybrid games)', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the game is available for booking')),
                ('image', models.ImageField(blank=True, help_text='Game photo', null=True, upload_to='games/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GameSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_custom', models.BooleanField(default=False, help_text='True for manually added slots')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SlotAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_capacity', models.PositiveIntegerField()),
                ('booked_spots', models.PositiveIntegerField(default=0)),
                ('is_private_booked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Slot Availability',
                'verbose_name_plural': 'Slot Availabilities',
            },
        ),
        migrations.AlterModelOptions(
            name='gamingstation',
            options={'ordering': ['station_type', 'name'], 'verbose_name': 'Gaming Station (DEPRECATED)', 'verbose_name_plural': 'Gaming Stations (DEPRECATED)'},
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='booking_end_after_start',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('PRIVATE', 'Private Booking (Full Capacity)'), ('SHARED', 'Shared Booking (Individual Spots)')], default='PRIVATE', help_text='Private (full capacity) or Shared (individual spots)', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='price_per_spot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per spot at time of booking', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='spots_booked',
            field=models.PositiveIntegerField(blank=True, help_text='Number of spots booked (1-capacity for shared, full capacity for private)', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='DEPRECATED: Use game_slot instead', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='gaming_station',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use game field instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.gamingstation'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DEPRECATED: Use price_per_spot instead', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_walk_in',
            field=models.BooleanField(default=False, help_text='DEPRECATED: Online-only bookings'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='DEPRECATED: Use game_slot instead', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount for the booking (price_per_spot * spots_booked)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='game',
            field=models.ForeignKey(blank=True, help_text='Game being booked', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.game'),
        ),
        migrations.AddField(
            model_name='gameslot',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='booking.game'),
        ),
        migrations.AddField(
            model_name='booking',
            name='game_slot',
            field=models.ForeignKey(blank=True, help_text='Specific time slot being booked', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.gameslot'),
        ),
        migrations.AddField(
            model_name='slotavailability',
            name='game_slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='booking.gameslot'),
        ),
        migrations.AlterUniqueTogether(
            name='gameslot',
            unique_together={('game', 'date', 'start_time')},
        ),
    ]
