# Generated by Django 5.2.7 on 2025-10-31 06:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TapNexSuperuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Commission percentage (e.g., 10.00 for 10%)', max_digits=5)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed platform fee per transaction', max_digits=8)),
                ('contact_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tapnex_superuser_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TapNex Superuser',
                'verbose_name_plural': 'TapNex Superusers',
            },
        ),
    ]
